# Generated by Django 5.2.1 on 2025-05-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_avatar_avatar_user_alter_avatar_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
