# Generated by Django 5.2.1 on 2025-05-30 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ertak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_favour', models.BooleanField(default=False)),
                ('img', models.URLField()),
                ('description', models.TextField()),
                ('stars', models.CharField(max_length=10)),
                ('main_text', models.TextField()),
                ('yosh', models.CharField(blank=True, max_length=100)),
                ('tip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Xulosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xulosa', models.TextField()),
                ('ertak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xulosalar', to='myapp.ertak')),
            ],
        ),
    ]
