# Generated by Django 5.2.1 on 2025-05-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='img',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
