# Generated by Django 5.2.1 on 2025-05-31 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_course_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
