# Generated by Django 5.2.1 on 2025-07-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_user_avatar_alter_user_tugulgankuni'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(related_name='items', to='myapp.item'),
        ),
    ]
