# Generated by Django 5.2.1 on 2025-07-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_user_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(related_name='item', to='myapp.item'),
        ),
    ]
